Fixed Section.GetContents trying to read NoBits section
konrad-kruczynski/elfsharp pull request #81
Opened 2021-11-08 19:54 UTC by dedmen

https://man7.org/linux/man-pages/man5/elf.5.html

Search for SHT_NOBITS

> sh_offset
>  This member's value holds the byte offset from the
              beginning of the file to the first byte in the section.
              One section type, SHT_NOBITS, occupies **no space in the
              file**, and its sh_offset member locates the conceptual
              placement in the file.

The old code tried to happily read a section from file, that simply isn't present in the file, which causes this to return bogus data.
I'm not sure if this is the correct approach to fix this, but the section isn't present in the file thus you cannot really return its contents.

2021-11-08 23:00 UTC, konrad-kruczynski commented
Thanks for the PR. Indeed there was a bug, actually it's quite funny that this didn't show up until now. Anyway I'll review it in a moment.

2021-11-08 23:04 UTC, konrad-kruczynski requested changes

2021-11-08 23:04 UTC, konrad-kruczynski commented on ELFSharp/ELF/Sections/Section.cs
> +                return new byte[] {};
```suggestion
            if (Type == SectionType.NoBits)
            {
                return Array.Empty<byte>();
            }
            
```

2021-11-08 23:04 UTC, konrad-kruczynski commented
Finished, just one small remark to consider.

2021-11-10 22:22 UTC, konrad-kruczynski commented
I'm merging it with my remark now.

2021-11-10 22:22 UTC, merged

2021-11-10 23:17 UTC, dedmen commented on ELFSharp/ELF/Sections/Section.cs
> +                return new byte[] {};
uh, didn't know this was a thing, learned something new! :D 
The best positive PR experience

2021-11-12 19:43 UTC, konrad-kruczynski commented
Released in `2.13.2`.