Support multiple NoteData within a NoteSegment
konrad-kruczynski/elfsharp pull request #87
Opened 2022-04-07 05:58 UTC by jerkerolofsson

**Added support for multiple NoteData within a single NoteSegment, as is common in ELF core dumps:**

- Added support for parsing multiple NodeData in NoteSegment and storing them in a List 
- Added INodeData interface to expose NodeData from a INoteSegment to package users
- Updated INodeSegment with a 'Nodes' property returning IReadOnlyList<INoteData> containing all the NoteData

2022-04-08 19:45 UTC, konrad-kruczynski requested changes
Thanks for the input, a few remarks here and there and I'll merge it :)

2022-04-08 19:45 UTC, konrad-kruczynski commented on ELFSharp/ELF/Sections/NoteData.cs
> +        public const ulong NOTE_DATA_HEADER_SIZE = 12; // name size + description size + field
Naming convention for constants in the project is `PascalCase`.

2022-04-08 19:45 UTC, konrad-kruczynski commented on ELFSharp/ELF/Segments/INoteData.cs
> +        string Name { get;}
```suggestion
        string Name { get; }
```

2022-04-08 19:45 UTC, konrad-kruczynski commented on ELFSharp/ELF/Segments/INoteData.cs
> +        string Name { get;}
```suggestion
        string Name { get; }
```

2022-04-08 19:45 UTC, konrad-kruczynski commented on ELFSharp/ELF/Sections/NoteData.cs
> +        public byte[] Description { get; private set; }
As we now go public, I'd like to go with something immutable (I know that we have it in `NoteSegment`, but this was a mistake. As `ImmutableArray` is not available in .NET Standard 2.0, I think that `ReadOnlyCollection` would be the best choice.

2022-04-08 19:45 UTC, konrad-kruczynski commented on ELFSharp/ELF/Sections/NoteData.cs
> +        public byte[] Description { get; private set; }
As we now go public, I'd like to go with something immutable (I know that we have it in `NoteSegment`, but this was a mistake. As `ImmutableArray` is not available in .NET Standard 2.0, I think that `ReadOnlyCollection` would be the best choice.

2022-04-08 19:45 UTC, konrad-kruczynski commented on ELFSharp/ELF/Segments/NoteSegment.cs
> +        private List<NoteData> mNotes = new List<NoteData>();
In this project private fields should be located at the end of the class. Also, don't prefix private fields with `m` or anything else, so just `notes`.

2022-04-08 19:45 UTC, konrad-kruczynski commented on ELFSharp/ELF/Segments/NoteSegment.cs
> +        private List<NoteData> mNotes = new List<NoteData>();
In this project private fields should be located at the end of the class. Also, don't prefix private fields with `m` or anything else, so just `notes`.

2022-04-08 19:45 UTC, konrad-kruczynski commented on ELFSharp/ELF/Segments/NoteSegment.cs
> +                        // File is damaged
I'd go with throwing exception here, unless you know that non-conforming files are frequent. Otherwise we'll wait for such an issue with accepting structure like here.

2022-04-08 19:45 UTC, konrad-kruczynski commented on ELFSharp/ELF/Segments/NoteSegment.cs
> +                        // File is damaged
I'd go with throwing here, unless you know that non-conforming files are frequent. Otherwise we'll wait for such an issue with accepting structure like here.

2022-04-11 04:09 UTC, jerkerolofsson commented on ELFSharp/ELF/Segments/NoteSegment.cs
> +                        // File is damaged
I can add an exception here. My reasoning for not doing it was that "if there are non-confirming files", that means that the change would be breaking behavior for backwards compatibility.

2022-04-11 04:18 UTC, jerkerolofsson commented
Requested changes commited in [b61c3cb](https://github.com/konrad-kruczynski/elfsharp/pull/87/commits/b61c3cb3e86819ba3b0ce9ebfe30935ae1dd2d9c)

2022-04-11 16:23 UTC, konrad-kruczynski approved these changes

2022-04-11 16:23 UTC, merged